# docker-compose.yml
version: '3.8'

services:

  # Message broker NATS 
  nats:
    image: nats:latest         # Image officielle NATS
    ports:
      - "4222:4222"            # Port principal pour les connexions des applications
      - "8222:8222"            # Port HTTP pour le monitoring (interface de stats)
    command: "--http_port 8222"  # Activer le monitoring HTTP

  # Base de données
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db    # Persistance des données entre redémarrages

volumes:
  mongo_data: